# render.yaml
services:
  - type: web
    name: alpine-container
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    rootDir: .
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8080